"""
Tools for parsing a YAML config file into a protobuf Config object, as defined in
fikl/proto/config.proto.
"""
from fikl.proto import config_pb2

import os
import yaml
import json
import tempfile
import logging

from google.protobuf.json_format import ParseDict


# def _check(config: dict) -> None:
#     """
#     Check that a config dictionary is valid.

#     Parameters
#     ----------
#     config : dict
#         Config dictionary to check, generated by load
#     """
#     # ensure that top level keys are valid


def load(config_yaml_path: str) -> config_pb2.Config:
    """
    Parse a YAML config file into a

    Parameters
    ----------
    config_yaml_path : str
        Path to the YAML config file.

    Returns
    -------
    Config
        Cap'n Proto Config object
    """
    config = config_pb2.Config()
    with open(config_yaml_path, "r") as config_yaml_f:
        config_dict = yaml.safe_load(config_yaml_f)
    ParseDict(config_dict, config)
    return config
