#!/bin/zsh

# get the directory of this script
REPO_DIR=$(realpath ${0:a:h}/..)
PROTO_DEF_DIR="$REPO_DIR/proto"
PROTO_OUT_DIR="$REPO_DIR/src/fikl/proto"

protoc \
    -I="$PROTO_DEF_DIR" \
    --python_out="$PROTO_OUT_DIR" \
    --pyi_out="$PROTO_OUT_DIR" \
    "$PROTO_DEF_DIR"/config.proto