#!/bin/zsh

set -e 
set -o pipefail

# assume that script is in top level
REPO_DIR=$(realpath ${0:a:h}/..)

# run pytest with coverage
python -m coverage run --source=$REPO_DIR/src -m pytest 
python -m coverage html

# rerun pytest with mypy
python -m pytest --mypy

# run pyright
python -m pyright
