#!/bin/zsh

set -e 
set -o pipefail

# assume that script is in top level
REPO_DIR=$(realpath ${0:a:h}/..)

python -m coverage run --source=$REPO_DIR/src -m pytest 
python -m coverage html
python -m pyright