#!/usr/bin/env python
from fikl.config import _yaml_to_json
import os
import argparse


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("yaml", help="Path to YAML config file")
    parser.add_argument("json", help="Path to JSON config file")
    return parser.parse_args()

def main():
    args = parse_args()
    _yaml_to_json(args.yaml, args.json)

if __name__ == "__main__":
    main()
